package com.manicure.business.entity;

import java.math.BigDecimal;

public class Business {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.id
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.name
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.lng
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    private BigDecimal lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.lat
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    private BigDecimal lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.province
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.city
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.district
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.street
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.street_number
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    private String streetNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.id
     *
     * @return the value of business.id
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.id
     *
     * @param id the value for business.id
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.name
     *
     * @return the value of business.name
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.name
     *
     * @param name the value for business.name
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.lng
     *
     * @return the value of business.lng
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public BigDecimal getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.lng
     *
     * @param lng the value for business.lng
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public void setLng(BigDecimal lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.lat
     *
     * @return the value of business.lat
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.lat
     *
     * @param lat the value for business.lat
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.province
     *
     * @return the value of business.province
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.province
     *
     * @param province the value for business.province
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.city
     *
     * @return the value of business.city
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.city
     *
     * @param city the value for business.city
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.district
     *
     * @return the value of business.district
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.district
     *
     * @param district the value for business.district
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.street
     *
     * @return the value of business.street
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.street
     *
     * @param street the value for business.street
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.street_number
     *
     * @return the value of business.street_number
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public String getStreetNumber() {
        return streetNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.street_number
     *
     * @param streetNumber the value for business.street_number
     *
     * @mbggenerated Sun Aug 02 15:50:38 CST 2015
     */
    public void setStreetNumber(String streetNumber) {
        this.streetNumber = streetNumber == null ? null : streetNumber.trim();
    }
}