package com.manicure.order.entity;

import java.util.Date;

public class OrderExtendTmp extends OrderExtendTmpKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_extend_tmp.order_id
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_extend_tmp.tec_id
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    private Integer tecId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_extend_tmp.buyer_nick
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    private String buyerNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_extend_tmp.name
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_extend_tmp.order_time
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_extend_tmp.order_type
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_extend_tmp.address
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_extend_tmp.tel
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_extend_tmp.order_id
     *
     * @return the value of order_extend_tmp.order_id
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_extend_tmp.order_id
     *
     * @param orderId the value for order_extend_tmp.order_id
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_extend_tmp.tec_id
     *
     * @return the value of order_extend_tmp.tec_id
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public Integer getTecId() {
        return tecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_extend_tmp.tec_id
     *
     * @param tecId the value for order_extend_tmp.tec_id
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public void setTecId(Integer tecId) {
        this.tecId = tecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_extend_tmp.buyer_nick
     *
     * @return the value of order_extend_tmp.buyer_nick
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_extend_tmp.buyer_nick
     *
     * @param buyerNick the value for order_extend_tmp.buyer_nick
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_extend_tmp.name
     *
     * @return the value of order_extend_tmp.name
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_extend_tmp.name
     *
     * @param name the value for order_extend_tmp.name
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_extend_tmp.order_time
     *
     * @return the value of order_extend_tmp.order_time
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_extend_tmp.order_time
     *
     * @param orderTime the value for order_extend_tmp.order_time
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_extend_tmp.order_type
     *
     * @return the value of order_extend_tmp.order_type
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_extend_tmp.order_type
     *
     * @param orderType the value for order_extend_tmp.order_type
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_extend_tmp.address
     *
     * @return the value of order_extend_tmp.address
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_extend_tmp.address
     *
     * @param address the value for order_extend_tmp.address
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_extend_tmp.tel
     *
     * @return the value of order_extend_tmp.tel
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_extend_tmp.tel
     *
     * @param tel the value for order_extend_tmp.tel
     *
     * @mbggenerated Fri Aug 07 12:18:24 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }
}