package com.manicure.order.entity;

import java.util.Date;

public class OrderExtend {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_extend.order_id
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_extend.tec_id
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	private Integer tecId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_extend.product_id
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	private String productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_extend.buyer_openid
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	private String buyerOpenid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_extend.buyer_nick
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	private String buyerNick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_extend.name
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_extend.order_time
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	private Date orderTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_extend.order_type
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	private Integer orderType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_extend.address
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_extend.tel
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	private String tel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_extend.order_id
	 * @return  the value of order_extend.order_id
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_extend.order_id
	 * @param orderId  the value for order_extend.order_id
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_extend.tec_id
	 * @return  the value of order_extend.tec_id
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public Integer getTecId() {
		return tecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_extend.tec_id
	 * @param tecId  the value for order_extend.tec_id
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public void setTecId(Integer tecId) {
		this.tecId = tecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_extend.product_id
	 * @return  the value of order_extend.product_id
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_extend.product_id
	 * @param productId  the value for order_extend.product_id
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public void setProductId(String productId) {
		this.productId = productId == null ? null : productId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_extend.buyer_openid
	 * @return  the value of order_extend.buyer_openid
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public String getBuyerOpenid() {
		return buyerOpenid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_extend.buyer_openid
	 * @param buyerOpenid  the value for order_extend.buyer_openid
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public void setBuyerOpenid(String buyerOpenid) {
		this.buyerOpenid = buyerOpenid == null ? null : buyerOpenid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_extend.buyer_nick
	 * @return  the value of order_extend.buyer_nick
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public String getBuyerNick() {
		return buyerNick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_extend.buyer_nick
	 * @param buyerNick  the value for order_extend.buyer_nick
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public void setBuyerNick(String buyerNick) {
		this.buyerNick = buyerNick == null ? null : buyerNick.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_extend.name
	 * @return  the value of order_extend.name
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_extend.name
	 * @param name  the value for order_extend.name
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_extend.order_time
	 * @return  the value of order_extend.order_time
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public Date getOrderTime() {
		return orderTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_extend.order_time
	 * @param orderTime  the value for order_extend.order_time
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_extend.order_type
	 * @return  the value of order_extend.order_type
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public Integer getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_extend.order_type
	 * @param orderType  the value for order_extend.order_type
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_extend.address
	 * @return  the value of order_extend.address
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_extend.address
	 * @param address  the value for order_extend.address
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_extend.tel
	 * @return  the value of order_extend.tel
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_extend.tel
	 * @param tel  the value for order_extend.tel
	 * @mbggenerated  Tue Aug 04 15:31:16 CST 2015
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}
}