package com.manicure.order.entity;

public class TecService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tec_service.id
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tec_service.tec_id
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    private Integer tecId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tec_service.product_id
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tec_service.id
     *
     * @return the value of tec_service.id
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tec_service.id
     *
     * @param id the value for tec_service.id
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tec_service.tec_id
     *
     * @return the value of tec_service.tec_id
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    public Integer getTecId() {
        return tecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tec_service.tec_id
     *
     * @param tecId the value for tec_service.tec_id
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    public void setTecId(Integer tecId) {
        this.tecId = tecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tec_service.product_id
     *
     * @return the value of tec_service.product_id
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tec_service.product_id
     *
     * @param productId the value for tec_service.product_id
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }
}