package com.manicure.favorite.entity;

import java.util.Date;

public class Favorite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.id
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.product_id
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.buyer_openid
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    private String buyerOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.time
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.id
     *
     * @return the value of favorite.id
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.id
     *
     * @param id the value for favorite.id
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.product_id
     *
     * @return the value of favorite.product_id
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.product_id
     *
     * @param productId the value for favorite.product_id
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.buyer_openid
     *
     * @return the value of favorite.buyer_openid
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    public String getBuyerOpenid() {
        return buyerOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.buyer_openid
     *
     * @param buyerOpenid the value for favorite.buyer_openid
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    public void setBuyerOpenid(String buyerOpenid) {
        this.buyerOpenid = buyerOpenid == null ? null : buyerOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.time
     *
     * @return the value of favorite.time
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.time
     *
     * @param time the value for favorite.time
     *
     * @mbggenerated Wed Aug 19 14:09:29 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }
}