package com.manicure.order.mapper;

import com.manicure.order.entity.OrderComment;
import com.manicure.order.entity.OrderCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_comment
     *
     * @mbggenerated Sun Aug 02 15:14:34 CST 2015
     */
    int countByExample(OrderCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_comment
     *
     * @mbggenerated Sun Aug 02 15:14:34 CST 2015
     */
    int deleteByExample(OrderCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_comment
     *
     * @mbggenerated Sun Aug 02 15:14:34 CST 2015
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_comment
     *
     * @mbggenerated Sun Aug 02 15:14:34 CST 2015
     */
    int insert(OrderComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_comment
     *
     * @mbggenerated Sun Aug 02 15:14:34 CST 2015
     */
    int insertSelective(OrderComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_comment
     *
     * @mbggenerated Sun Aug 02 15:14:34 CST 2015
     */
    List<OrderComment> selectByExample(OrderCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_comment
     *
     * @mbggenerated Sun Aug 02 15:14:34 CST 2015
     */
    OrderComment selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_comment
     *
     * @mbggenerated Sun Aug 02 15:14:34 CST 2015
     */
    int updateByExampleSelective(@Param("record") OrderComment record, @Param("example") OrderCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_comment
     *
     * @mbggenerated Sun Aug 02 15:14:34 CST 2015
     */
    int updateByExample(@Param("record") OrderComment record, @Param("example") OrderCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_comment
     *
     * @mbggenerated Sun Aug 02 15:14:34 CST 2015
     */
    int updateByPrimaryKeySelective(OrderComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_comment
     *
     * @mbggenerated Sun Aug 02 15:14:34 CST 2015
     */
    int updateByPrimaryKey(OrderComment record);
}