package com.manicure.order.mapper;

import com.manicure.order.entity.TecService;
import com.manicure.order.entity.TecServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TecServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_service
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    int countByExample(TecServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_service
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    int deleteByExample(TecServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_service
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_service
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    int insert(TecService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_service
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    int insertSelective(TecService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_service
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    List<TecService> selectByExample(TecServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_service
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    TecService selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_service
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") TecService record, @Param("example") TecServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_service
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    int updateByExample(@Param("record") TecService record, @Param("example") TecServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_service
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    int updateByPrimaryKeySelective(TecService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_service
     *
     * @mbggenerated Thu Aug 06 20:23:31 CST 2015
     */
    int updateByPrimaryKey(TecService record);
}