package com.manicure.technician.entity;

import java.math.BigDecimal;

public class Technician {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.id
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.name
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.service_type
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private Integer serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.protal_id
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private String protalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.job_title
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private String jobTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.origin
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.constellation
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private String constellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.love
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private String love;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.self_desc
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private String selfDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.header_pic
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private String headerPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.self_pic1
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private String selfPic1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.self_pic2
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private String selfPic2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technician.self_pic3
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    private String selfPic3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.id
     *
     * @return the value of technician.id
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.id
     *
     * @param id the value for technician.id
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.name
     *
     * @return the value of technician.name
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.name
     *
     * @param name the value for technician.name
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.service_type
     *
     * @return the value of technician.service_type
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public Integer getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.service_type
     *
     * @param serviceType the value for technician.service_type
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setServiceType(Integer serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.protal_id
     *
     * @return the value of technician.protal_id
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getProtalId() {
        return protalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.protal_id
     *
     * @param protalId the value for technician.protal_id
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setProtalId(String protalId) {
        this.protalId = protalId == null ? null : protalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.job_title
     *
     * @return the value of technician.job_title
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.job_title
     *
     * @param jobTitle the value for technician.job_title
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.origin
     *
     * @return the value of technician.origin
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.origin
     *
     * @param origin the value for technician.origin
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.constellation
     *
     * @return the value of technician.constellation
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getConstellation() {
        return constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.constellation
     *
     * @param constellation the value for technician.constellation
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setConstellation(String constellation) {
        this.constellation = constellation == null ? null : constellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.love
     *
     * @return the value of technician.love
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getLove() {
        return love;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.love
     *
     * @param love the value for technician.love
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setLove(String love) {
        this.love = love == null ? null : love.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.self_desc
     *
     * @return the value of technician.self_desc
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getSelfDesc() {
        return selfDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.self_desc
     *
     * @param selfDesc the value for technician.self_desc
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setSelfDesc(String selfDesc) {
        this.selfDesc = selfDesc == null ? null : selfDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.header_pic
     *
     * @return the value of technician.header_pic
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getHeaderPic() {
        return headerPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.header_pic
     *
     * @param headerPic the value for technician.header_pic
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setHeaderPic(String headerPic) {
        this.headerPic = headerPic == null ? null : headerPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.self_pic1
     *
     * @return the value of technician.self_pic1
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getSelfPic1() {
        return selfPic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.self_pic1
     *
     * @param selfPic1 the value for technician.self_pic1
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setSelfPic1(String selfPic1) {
        this.selfPic1 = selfPic1 == null ? null : selfPic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.self_pic2
     *
     * @return the value of technician.self_pic2
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getSelfPic2() {
        return selfPic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.self_pic2
     *
     * @param selfPic2 the value for technician.self_pic2
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setSelfPic2(String selfPic2) {
        this.selfPic2 = selfPic2 == null ? null : selfPic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technician.self_pic3
     *
     * @return the value of technician.self_pic3
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getSelfPic3() {
        return selfPic3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technician.self_pic3
     *
     * @param selfPic3 the value for technician.self_pic3
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setSelfPic3(String selfPic3) {
        this.selfPic3 = selfPic3 == null ? null : selfPic3.trim();
    }

    // add by zhangqw below
	private Integer commentCount;
    private Integer orderCount;
    // 评价总分数
    private Integer evaluation; 
    private BigDecimal stars;
    private BigDecimal profnalScore;
    private BigDecimal moveScore;
    private BigDecimal punctualScore;
    // 商圈
    private String business;
	public Integer getCommentCount() {
		return commentCount;
	}

	public void setCommentCount(Integer commentCount) {
		this.commentCount = commentCount;
	}

	public Integer getOrderCount() {
		return orderCount;
	}

	public void setOrderCount(Integer orderCount) {
		this.orderCount = orderCount;
	}

	public Integer getEvaluation() {
		return evaluation;
	}

	public void setEvaluation(Integer evaluation) {
		this.evaluation = evaluation;
	}

	public BigDecimal getStars() {
		return stars;
	}

	public void setStars(BigDecimal stars) {
		this.stars = stars;
	}

	public BigDecimal getProfnalScore() {
		return profnalScore;
	}

	public void setProfnalScore(BigDecimal profnalScore) {
		this.profnalScore = profnalScore;
	}

	public BigDecimal getMoveScore() {
		return moveScore;
	}

	public void setMoveScore(BigDecimal moveScore) {
		this.moveScore = moveScore;
	}

	public BigDecimal getPunctualScore() {
		return punctualScore;
	}

	public void setPunctualScore(BigDecimal punctualScore) {
		this.punctualScore = punctualScore;
	}

	public String getBusiness() {
		return business;
	}

	public void setBusiness(String business) {
		this.business = business;
	}
    
    
}