package com.manicure.technician.entity;

import java.util.ArrayList;
import java.util.List;

public class TechnicianExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public TechnicianExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIsNull() {
            addCriterion("service_type is null");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIsNotNull() {
            addCriterion("service_type is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTypeEqualTo(Integer value) {
            addCriterion("service_type =", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotEqualTo(Integer value) {
            addCriterion("service_type <>", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeGreaterThan(Integer value) {
            addCriterion("service_type >", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_type >=", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeLessThan(Integer value) {
            addCriterion("service_type <", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeLessThanOrEqualTo(Integer value) {
            addCriterion("service_type <=", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIn(List<Integer> values) {
            addCriterion("service_type in", values, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotIn(List<Integer> values) {
            addCriterion("service_type not in", values, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeBetween(Integer value1, Integer value2) {
            addCriterion("service_type between", value1, value2, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("service_type not between", value1, value2, "serviceType");
            return (Criteria) this;
        }

        public Criteria andProtalIdIsNull() {
            addCriterion("protal_id is null");
            return (Criteria) this;
        }

        public Criteria andProtalIdIsNotNull() {
            addCriterion("protal_id is not null");
            return (Criteria) this;
        }

        public Criteria andProtalIdEqualTo(String value) {
            addCriterion("protal_id =", value, "protalId");
            return (Criteria) this;
        }

        public Criteria andProtalIdNotEqualTo(String value) {
            addCriterion("protal_id <>", value, "protalId");
            return (Criteria) this;
        }

        public Criteria andProtalIdGreaterThan(String value) {
            addCriterion("protal_id >", value, "protalId");
            return (Criteria) this;
        }

        public Criteria andProtalIdGreaterThanOrEqualTo(String value) {
            addCriterion("protal_id >=", value, "protalId");
            return (Criteria) this;
        }

        public Criteria andProtalIdLessThan(String value) {
            addCriterion("protal_id <", value, "protalId");
            return (Criteria) this;
        }

        public Criteria andProtalIdLessThanOrEqualTo(String value) {
            addCriterion("protal_id <=", value, "protalId");
            return (Criteria) this;
        }

        public Criteria andProtalIdLike(String value) {
            addCriterion("protal_id like", value, "protalId");
            return (Criteria) this;
        }

        public Criteria andProtalIdNotLike(String value) {
            addCriterion("protal_id not like", value, "protalId");
            return (Criteria) this;
        }

        public Criteria andProtalIdIn(List<String> values) {
            addCriterion("protal_id in", values, "protalId");
            return (Criteria) this;
        }

        public Criteria andProtalIdNotIn(List<String> values) {
            addCriterion("protal_id not in", values, "protalId");
            return (Criteria) this;
        }

        public Criteria andProtalIdBetween(String value1, String value2) {
            addCriterion("protal_id between", value1, value2, "protalId");
            return (Criteria) this;
        }

        public Criteria andProtalIdNotBetween(String value1, String value2) {
            addCriterion("protal_id not between", value1, value2, "protalId");
            return (Criteria) this;
        }

        public Criteria andJobTitleIsNull() {
            addCriterion("job_title is null");
            return (Criteria) this;
        }

        public Criteria andJobTitleIsNotNull() {
            addCriterion("job_title is not null");
            return (Criteria) this;
        }

        public Criteria andJobTitleEqualTo(String value) {
            addCriterion("job_title =", value, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andJobTitleNotEqualTo(String value) {
            addCriterion("job_title <>", value, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andJobTitleGreaterThan(String value) {
            addCriterion("job_title >", value, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andJobTitleGreaterThanOrEqualTo(String value) {
            addCriterion("job_title >=", value, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andJobTitleLessThan(String value) {
            addCriterion("job_title <", value, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andJobTitleLessThanOrEqualTo(String value) {
            addCriterion("job_title <=", value, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andJobTitleLike(String value) {
            addCriterion("job_title like", value, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andJobTitleNotLike(String value) {
            addCriterion("job_title not like", value, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andJobTitleIn(List<String> values) {
            addCriterion("job_title in", values, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andJobTitleNotIn(List<String> values) {
            addCriterion("job_title not in", values, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andJobTitleBetween(String value1, String value2) {
            addCriterion("job_title between", value1, value2, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andJobTitleNotBetween(String value1, String value2) {
            addCriterion("job_title not between", value1, value2, "jobTitle");
            return (Criteria) this;
        }

        public Criteria andOriginIsNull() {
            addCriterion("origin is null");
            return (Criteria) this;
        }

        public Criteria andOriginIsNotNull() {
            addCriterion("origin is not null");
            return (Criteria) this;
        }

        public Criteria andOriginEqualTo(String value) {
            addCriterion("origin =", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotEqualTo(String value) {
            addCriterion("origin <>", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginGreaterThan(String value) {
            addCriterion("origin >", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginGreaterThanOrEqualTo(String value) {
            addCriterion("origin >=", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginLessThan(String value) {
            addCriterion("origin <", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginLessThanOrEqualTo(String value) {
            addCriterion("origin <=", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginLike(String value) {
            addCriterion("origin like", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotLike(String value) {
            addCriterion("origin not like", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginIn(List<String> values) {
            addCriterion("origin in", values, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotIn(List<String> values) {
            addCriterion("origin not in", values, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginBetween(String value1, String value2) {
            addCriterion("origin between", value1, value2, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotBetween(String value1, String value2) {
            addCriterion("origin not between", value1, value2, "origin");
            return (Criteria) this;
        }

        public Criteria andConstellationIsNull() {
            addCriterion("constellation is null");
            return (Criteria) this;
        }

        public Criteria andConstellationIsNotNull() {
            addCriterion("constellation is not null");
            return (Criteria) this;
        }

        public Criteria andConstellationEqualTo(String value) {
            addCriterion("constellation =", value, "constellation");
            return (Criteria) this;
        }

        public Criteria andConstellationNotEqualTo(String value) {
            addCriterion("constellation <>", value, "constellation");
            return (Criteria) this;
        }

        public Criteria andConstellationGreaterThan(String value) {
            addCriterion("constellation >", value, "constellation");
            return (Criteria) this;
        }

        public Criteria andConstellationGreaterThanOrEqualTo(String value) {
            addCriterion("constellation >=", value, "constellation");
            return (Criteria) this;
        }

        public Criteria andConstellationLessThan(String value) {
            addCriterion("constellation <", value, "constellation");
            return (Criteria) this;
        }

        public Criteria andConstellationLessThanOrEqualTo(String value) {
            addCriterion("constellation <=", value, "constellation");
            return (Criteria) this;
        }

        public Criteria andConstellationLike(String value) {
            addCriterion("constellation like", value, "constellation");
            return (Criteria) this;
        }

        public Criteria andConstellationNotLike(String value) {
            addCriterion("constellation not like", value, "constellation");
            return (Criteria) this;
        }

        public Criteria andConstellationIn(List<String> values) {
            addCriterion("constellation in", values, "constellation");
            return (Criteria) this;
        }

        public Criteria andConstellationNotIn(List<String> values) {
            addCriterion("constellation not in", values, "constellation");
            return (Criteria) this;
        }

        public Criteria andConstellationBetween(String value1, String value2) {
            addCriterion("constellation between", value1, value2, "constellation");
            return (Criteria) this;
        }

        public Criteria andConstellationNotBetween(String value1, String value2) {
            addCriterion("constellation not between", value1, value2, "constellation");
            return (Criteria) this;
        }

        public Criteria andLoveIsNull() {
            addCriterion("love is null");
            return (Criteria) this;
        }

        public Criteria andLoveIsNotNull() {
            addCriterion("love is not null");
            return (Criteria) this;
        }

        public Criteria andLoveEqualTo(String value) {
            addCriterion("love =", value, "love");
            return (Criteria) this;
        }

        public Criteria andLoveNotEqualTo(String value) {
            addCriterion("love <>", value, "love");
            return (Criteria) this;
        }

        public Criteria andLoveGreaterThan(String value) {
            addCriterion("love >", value, "love");
            return (Criteria) this;
        }

        public Criteria andLoveGreaterThanOrEqualTo(String value) {
            addCriterion("love >=", value, "love");
            return (Criteria) this;
        }

        public Criteria andLoveLessThan(String value) {
            addCriterion("love <", value, "love");
            return (Criteria) this;
        }

        public Criteria andLoveLessThanOrEqualTo(String value) {
            addCriterion("love <=", value, "love");
            return (Criteria) this;
        }

        public Criteria andLoveLike(String value) {
            addCriterion("love like", value, "love");
            return (Criteria) this;
        }

        public Criteria andLoveNotLike(String value) {
            addCriterion("love not like", value, "love");
            return (Criteria) this;
        }

        public Criteria andLoveIn(List<String> values) {
            addCriterion("love in", values, "love");
            return (Criteria) this;
        }

        public Criteria andLoveNotIn(List<String> values) {
            addCriterion("love not in", values, "love");
            return (Criteria) this;
        }

        public Criteria andLoveBetween(String value1, String value2) {
            addCriterion("love between", value1, value2, "love");
            return (Criteria) this;
        }

        public Criteria andLoveNotBetween(String value1, String value2) {
            addCriterion("love not between", value1, value2, "love");
            return (Criteria) this;
        }

        public Criteria andSelfDescIsNull() {
            addCriterion("self_desc is null");
            return (Criteria) this;
        }

        public Criteria andSelfDescIsNotNull() {
            addCriterion("self_desc is not null");
            return (Criteria) this;
        }

        public Criteria andSelfDescEqualTo(String value) {
            addCriterion("self_desc =", value, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andSelfDescNotEqualTo(String value) {
            addCriterion("self_desc <>", value, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andSelfDescGreaterThan(String value) {
            addCriterion("self_desc >", value, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andSelfDescGreaterThanOrEqualTo(String value) {
            addCriterion("self_desc >=", value, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andSelfDescLessThan(String value) {
            addCriterion("self_desc <", value, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andSelfDescLessThanOrEqualTo(String value) {
            addCriterion("self_desc <=", value, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andSelfDescLike(String value) {
            addCriterion("self_desc like", value, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andSelfDescNotLike(String value) {
            addCriterion("self_desc not like", value, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andSelfDescIn(List<String> values) {
            addCriterion("self_desc in", values, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andSelfDescNotIn(List<String> values) {
            addCriterion("self_desc not in", values, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andSelfDescBetween(String value1, String value2) {
            addCriterion("self_desc between", value1, value2, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andSelfDescNotBetween(String value1, String value2) {
            addCriterion("self_desc not between", value1, value2, "selfDesc");
            return (Criteria) this;
        }

        public Criteria andHeaderPicIsNull() {
            addCriterion("header_pic is null");
            return (Criteria) this;
        }

        public Criteria andHeaderPicIsNotNull() {
            addCriterion("header_pic is not null");
            return (Criteria) this;
        }

        public Criteria andHeaderPicEqualTo(String value) {
            addCriterion("header_pic =", value, "headerPic");
            return (Criteria) this;
        }

        public Criteria andHeaderPicNotEqualTo(String value) {
            addCriterion("header_pic <>", value, "headerPic");
            return (Criteria) this;
        }

        public Criteria andHeaderPicGreaterThan(String value) {
            addCriterion("header_pic >", value, "headerPic");
            return (Criteria) this;
        }

        public Criteria andHeaderPicGreaterThanOrEqualTo(String value) {
            addCriterion("header_pic >=", value, "headerPic");
            return (Criteria) this;
        }

        public Criteria andHeaderPicLessThan(String value) {
            addCriterion("header_pic <", value, "headerPic");
            return (Criteria) this;
        }

        public Criteria andHeaderPicLessThanOrEqualTo(String value) {
            addCriterion("header_pic <=", value, "headerPic");
            return (Criteria) this;
        }

        public Criteria andHeaderPicLike(String value) {
            addCriterion("header_pic like", value, "headerPic");
            return (Criteria) this;
        }

        public Criteria andHeaderPicNotLike(String value) {
            addCriterion("header_pic not like", value, "headerPic");
            return (Criteria) this;
        }

        public Criteria andHeaderPicIn(List<String> values) {
            addCriterion("header_pic in", values, "headerPic");
            return (Criteria) this;
        }

        public Criteria andHeaderPicNotIn(List<String> values) {
            addCriterion("header_pic not in", values, "headerPic");
            return (Criteria) this;
        }

        public Criteria andHeaderPicBetween(String value1, String value2) {
            addCriterion("header_pic between", value1, value2, "headerPic");
            return (Criteria) this;
        }

        public Criteria andHeaderPicNotBetween(String value1, String value2) {
            addCriterion("header_pic not between", value1, value2, "headerPic");
            return (Criteria) this;
        }

        public Criteria andSelfPic1IsNull() {
            addCriterion("self_pic1 is null");
            return (Criteria) this;
        }

        public Criteria andSelfPic1IsNotNull() {
            addCriterion("self_pic1 is not null");
            return (Criteria) this;
        }

        public Criteria andSelfPic1EqualTo(String value) {
            addCriterion("self_pic1 =", value, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic1NotEqualTo(String value) {
            addCriterion("self_pic1 <>", value, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic1GreaterThan(String value) {
            addCriterion("self_pic1 >", value, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic1GreaterThanOrEqualTo(String value) {
            addCriterion("self_pic1 >=", value, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic1LessThan(String value) {
            addCriterion("self_pic1 <", value, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic1LessThanOrEqualTo(String value) {
            addCriterion("self_pic1 <=", value, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic1Like(String value) {
            addCriterion("self_pic1 like", value, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic1NotLike(String value) {
            addCriterion("self_pic1 not like", value, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic1In(List<String> values) {
            addCriterion("self_pic1 in", values, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic1NotIn(List<String> values) {
            addCriterion("self_pic1 not in", values, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic1Between(String value1, String value2) {
            addCriterion("self_pic1 between", value1, value2, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic1NotBetween(String value1, String value2) {
            addCriterion("self_pic1 not between", value1, value2, "selfPic1");
            return (Criteria) this;
        }

        public Criteria andSelfPic2IsNull() {
            addCriterion("self_pic2 is null");
            return (Criteria) this;
        }

        public Criteria andSelfPic2IsNotNull() {
            addCriterion("self_pic2 is not null");
            return (Criteria) this;
        }

        public Criteria andSelfPic2EqualTo(String value) {
            addCriterion("self_pic2 =", value, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic2NotEqualTo(String value) {
            addCriterion("self_pic2 <>", value, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic2GreaterThan(String value) {
            addCriterion("self_pic2 >", value, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic2GreaterThanOrEqualTo(String value) {
            addCriterion("self_pic2 >=", value, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic2LessThan(String value) {
            addCriterion("self_pic2 <", value, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic2LessThanOrEqualTo(String value) {
            addCriterion("self_pic2 <=", value, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic2Like(String value) {
            addCriterion("self_pic2 like", value, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic2NotLike(String value) {
            addCriterion("self_pic2 not like", value, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic2In(List<String> values) {
            addCriterion("self_pic2 in", values, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic2NotIn(List<String> values) {
            addCriterion("self_pic2 not in", values, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic2Between(String value1, String value2) {
            addCriterion("self_pic2 between", value1, value2, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic2NotBetween(String value1, String value2) {
            addCriterion("self_pic2 not between", value1, value2, "selfPic2");
            return (Criteria) this;
        }

        public Criteria andSelfPic3IsNull() {
            addCriterion("self_pic3 is null");
            return (Criteria) this;
        }

        public Criteria andSelfPic3IsNotNull() {
            addCriterion("self_pic3 is not null");
            return (Criteria) this;
        }

        public Criteria andSelfPic3EqualTo(String value) {
            addCriterion("self_pic3 =", value, "selfPic3");
            return (Criteria) this;
        }

        public Criteria andSelfPic3NotEqualTo(String value) {
            addCriterion("self_pic3 <>", value, "selfPic3");
            return (Criteria) this;
        }

        public Criteria andSelfPic3GreaterThan(String value) {
            addCriterion("self_pic3 >", value, "selfPic3");
            return (Criteria) this;
        }

        public Criteria andSelfPic3GreaterThanOrEqualTo(String value) {
            addCriterion("self_pic3 >=", value, "selfPic3");
            return (Criteria) this;
        }

        public Criteria andSelfPic3LessThan(String value) {
            addCriterion("self_pic3 <", value, "selfPic3");
            return (Criteria) this;
        }

        public Criteria andSelfPic3LessThanOrEqualTo(String value) {
            addCriterion("self_pic3 <=", value, "selfPic3");
            return (Criteria) this;
        }

        public Criteria andSelfPic3Like(String value) {
            addCriterion("self_pic3 like", value, "selfPic3");
            return (Criteria) this;
        }

        public Criteria andSelfPic3NotLike(String value) {
            addCriterion("self_pic3 not like", value, "selfPic3");
            return (Criteria) this;
        }

        public Criteria andSelfPic3In(List<String> values) {
            addCriterion("self_pic3 in", values, "selfPic3");
            return (Criteria) this;
        }

        public Criteria andSelfPic3NotIn(List<String> values) {
            addCriterion("self_pic3 not in", values, "selfPic3");
            return (Criteria) this;
        }

        public Criteria andSelfPic3Between(String value1, String value2) {
            addCriterion("self_pic3 between", value1, value2, "selfPic3");
            return (Criteria) this;
        }

        public Criteria andSelfPic3NotBetween(String value1, String value2) {
            addCriterion("self_pic3 not between", value1, value2, "selfPic3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table technician
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 30 16:33:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table technician
     *
     * @mbggenerated Thu Jul 30 16:33:22 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}